<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.cap.test.bankapp.DemoTestCases" tests="4" skipped="0" failures="1" errors="0" timestamp="2016-09-01T12:26:16" hostname="LIN73000499" time="0.01">
  <properties/>
  <testcase name="testTime" classname="org.cap.test.bankapp.DemoTestCases" time="0.005">
    <failure message="org.junit.runners.model.TestTimedOutException: test timed out after 1 milliseconds" type="org.junit.runners.model.TestTimedOutException">org.junit.runners.model.TestTimedOutException: test timed out after 1 milliseconds
	at org.cap.test.bankapp.DemoTestCases.testTime(DemoTestCases.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
</failure>
  </testcase>
  <testcase name="test" classname="org.cap.test.bankapp.DemoTestCases" time="0.0"/>
  <testcase name="testTime" classname="org.cap.test.bankapp.DemoTestCases" time="0.001"/>
  <testcase name="test" classname="org.cap.test.bankapp.DemoTestCases" time="0.0"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
